# basic options
set -g base-index 1
setw -g pane-base-index 1
set -g status-left " #[fg=green]#(tmux ls | awk -F: '{print $1}' | tr '\\n' ' ') "

# Mouse
set -g mouse on

# Support vim-related keybindings
set -g mode-keys vi
set -g status-keys vi

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

set -g default-terminal "screen-256color"
set -as terminal-overrides ",xterm-256color:Tc"

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin "janoamaral/tokyo-night-tmux"

#colorscheme
set -g @tokyo-night-tmux_theme night   # night (default) | storm | moon | day
#set -g @tokyo-night-tmux_transparent 1 # transparent background
set -g @tokyo-night-tmux_show_git 1             # local git status
set -g @tokyo-night-tmux_show_wbg 1             # GitHub / GitLab stats
set -g @tokyo-night-tmux_show_netspeed 1        # network speed
set -g @tokyo-night-tmux_show_battery_widget 1  # battery level
set -g @tokyo-night-tmux_show_music 1           # now playing
set -g @tokyo-night-tmux_show_path 1            # current path
set -g @tokyo-night-tmux_show_hostname 1        # machine hostname

# Other examples:
# set -g @plugin 'github_username/plugin_name'
# set -g @plugin 'github_username/plugin_name#branch'
# set -g @plugin 'git@github.com:user/plugin'
# set -g @plugin 'git@bitbucket.com:user/plugin'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
