# Add truecolor support
set-option -ga terminal-overrides ",xterm-256color:Tc"
# Default terminal is 256 colors
set -g default-terminal "xterm-256color"

set -g base-index 1
setw -g pane-base-index 1

# Mouse
set -g mouse on

# Support vim-related keybindings
set -g mode-keys vi
set -g status-keys vi

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

